spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/dbKeenayEducation
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: demo
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  security:
    key: 8074658237c236e39e96e909ac1abb25a3e1773b100096ad6877c439cd452c17

server:
  port: 8080

logging:
  level:
    keenay.education: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%mdc] %msg%n"